### ISSUE TITLE
filter: Boolean return value for Func is inverse compared to common similar code.

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/httpfs#3]
Issue raised by @neelance. He said:

> `filter.New` is a bit strange, I'd expect the bool to be the other way around: true => include
> usually all filter functions that I know use `true` as "keep"

He provided these examples:

- https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
- http://ruby-doc.org/core-2.2.0/Array.html#method-i-select

I think that's a reasonable suggestion for an improvement. But I don't use `filter` package much, so if there are strong other opinions, we can punt on this.

**Comment by shurcooL** [comment]
Actually, I realize now that this is not so black and white.

Consider the following 2 situations:

1. You want to keep only the root directory and `src` directory with all of its contents, but filter everything else out.

2. You want to keep all files except those with `.go` and `.html` extension.

The first situation is easier to express with a `KeepIf ... true` relationship. Keep only those files that you're interested in, return true for them, etc., other files get skipped.

However, for second situation, it's much easier to express as ignore only files that have .go or .html extension, but keep all others.

To that end, I propose the following resolution:

Replace https://godoc.org/github.com/shurcooL/httpfs/filter#New with two constructors:

```Go
// Keep creates a filesystem that contains only those files in source for which
// keep returns true.
func Keep(source http.FileSystem, keep Func) http.FileSystem {
	return &filterFS{source: source, ignore: func(path string, fi os.FileInfo) bool { return !keep(path, fi) } }
}

// Ignore creates a filesystem that contains everything in source, except files for which
// ignore returns true.
func Ignore(source http.FileSystem, ignore Func) http.FileSystem {
	return &filterFS{source: source, ignore: ignore}
}
```

Usage is easy and readable IMO:

```Go
// FS is a virtual filesystem that contains native packages.
var FS = filter.Keep(
	http.Dir(importPathToDir("github.com/gopherjs/gopherjs/compiler/natives")),
	func(path string, fi os.FileInfo) bool {
		return path == "/" || path == "/src" || strings.HasPrefix(path, "/src/")
	},
)
```

```Go
// Ignore .go files, .html files, and directories named "folder-to-skip".
ignoreFn := func(_ string, fi os.FileInfo) bool {
	return pathpkg.Ext(fi.Name()) == ".go" || pathpkg.Ext(fi.Name()) == ".html" ||
		(fi.IsDir() && fi.Name() == "folder-to-skip")
}

fs = filter.Ignore(fs, ignoreFn)
```

Thoughts? /cc @neelance @slimsag

**Comment by slimsag** [comment]
Your proposal here with `filter.Keep` and `filter.Ignore` (maybe `filter.Drop`?) sounds good to me. I remember when we implemented this there was a bit of ambiguity regarding `filter.New`, but actually the default used in other languages (ruby, JS) is actually confusing from an English perspective! `true` means "yes", and filter inherently means _'to take something out'_

> definition: pass (a liquid, gas, light, or sound) through a device to remove unwanted material.

So IMO `filter = true` would mean to take something out. But I agree it's inconsistent! Let's go with your proposal :)
