### ISSUE TITLE
vfsutil: Remove dependency on godoc/vfs

### ISSUE THREAD

**Issue by johanbrandhorst** [shurcooL/httpfs#6]
As far as I can tell, the only type used (in non-test code) is the `vfs.ReadSeekCloser`, an interface which can easily be duplicated to avoid this unnecessary dependency, and reduce the dependency tree when importing the package.

**Comment by shurcooL** [comment]
That looks like a good idea. Thank you for finding and reporting this opportunity to improve the code @johanbrandhorst!

**Comment by shurcooL** [comment]
Resolved in 809beceb23714880abc4a382a00c05f89d13b1cc. Compare package imports [before](https://gotools.org/github.com/shurcooL/httpfs/vfsutil?rev=809beceb23714880abc4a382a00c05f89d13b1cc^&tab=imports) and [after](https://gotools.org/github.com/shurcooL/httpfs/vfsutil?rev=809beceb23714880abc4a382a00c05f89d13b1cc&tab=imports).
