### ISSUE TITLE
vfsutil: ReadDir compatibility issue with statik/fs

### ISSUE THREAD

**Issue by shakahl** [shurcooL/httpfs#8]
Hi Everybody!

I noticed that the `vfsutil.ReadDir`  used by `vfstemplate.ParseGlob` is incompatible with `https://github.com/rakyll/statik` binary file embedding tool. 

**The problem**

```go
// ReadDir reads the contents of the directory associated with file and
// returns a slice of FileInfo values in directory order.
func ReadDir(fs http.FileSystem, name string) ([]os.FileInfo, error) {
	f, err := fs.Open(name)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return f.Readdir(0)
}
```
Notice the `f.Readdir(0)`. Some other libraries are ignoring the `0` count like **rakyll/statik**.

Although the file interface allows `0` for specifying the count but it would be better to specify `-1` here to be more compatible with other tools.

Relevant documentation can be found here: https://golang.org/pkg/os/#File.Readdir

**Summary**

`f.Readdir(0)` should `f.Readdir(-1)`.

The problem occured in the project called **statik**. Check out their implementation: https://github.com/rakyll/statik/blob/3bac566d30cdbeddef402a80f3d6305860e59f12/fs/fs.go#L190

I will make a pullrequest for them too.

**Comment by shakahl** [comment]
Pull request:  #9

**Comment by dmitshur** [comment]
Hi @shakahl,

Thanks for the issue report. As far as I can tell, calling the `Readdir` method with 0 or any negative value should have the same effect. As you pointed out, that's what its documentation suggests:

> If n <= 0, Readdir returns all the FileInfo from the directory in a single slice.

Given that, if the current `rakyll/statik` implementation doesn't treat 0 and -1 the same, I think it would make more sense to change it so that it does. What do you think?

/cc @rakyll

**Comment by shakahl** [comment]
I agree. I wont break any existing stuff just makes more compatible with another good library. Anyway I will make a pull request for `rakyll/statik` as well.

**Comment by dmitshur** [comment]
Fixed via https://github.com/rakyll/statik/pull/69.
